### ISSUE TITLE
Invalid "Send to Memory Window" string when indexing raw pointers to structs in watch window

### ISSUE THREAD

**Issue by McKay42** [x13pixels/remedybg-issues#257]
Toolchain: [x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/) and [cv2pdb-0.51.zip](https://github.com/rainers/cv2pdb/releases/tag/v0.51)

main.cpp:
```
struct SOMETHING
{
	int value;
};

int main(void)
{
	SOMETHING arrayOfSomethings[3];
	
	for (int i=0; i<3; i++)
	{
		arrayOfSomethings[i].value = i;
	}
	
	return 0;
}
```

build.bat:
```
g++ -g3 -O0 -o example.exe main.cpp
cv2pdb example.exe
remedybg example.exe
```

<img width="875" alt="Capture" src="https://user-images.githubusercontent.com/16856443/179223993-27e4a83e-ad5f-4bdc-9e7f-6f5d4e7839a3.PNG">

The "Send to Memory Window" function sends an invalid (mangled cut off) string to the Address textbox of the memory window when used on any other element besides the first element _in a raw/literal pointer to an array of structs_. In the screenshot, the `arrayOfSomethings` is at `0x000000000060fe10` and has `3` elements, so entering `(SOMETHING*)0x000000000060fe10, 3` let's me view the array in the watch window. Right click > "Send to Memory Window" on any of the expanded "value" fields except the first one generates a mangled address string. This does not happen in e.g. `__locals` or when directly watching `arrayOfSomethings` by name.

Expected: `&(((SOMETHING*)0x000000000060fe10)[1].value)`
Actual: `&(((SOMETHING*)0x000000000060fe1[1].value)`

It seems to cut off the last digit as well as the closing parenthesis `0)`.

**Comment by x13pixels** [comment]
Fixed in 0.3.8.0

**Comment by McKay42** [comment]
This is not yet fixed, see behavior in 0.3.8.0:

<img width="1018" alt="Capture" src="https://user-images.githubusercontent.com/16856443/184430856-436c0818-f39a-4d12-8cff-0e006c02d97e.PNG">

Produces the following values depending on which element "Send to Memory Window" is used on:
1) `&(((SOMETHING*)0x000000000060FE10)[0].value)` (correct)
2) `&(((SOMETHING*)0x000000000060FE10)[0].[1].value)` (expected`[1].value` instead of `[0].[1].value`)
3) `&(((SOMETHING*)0x000000000060FE10)[0].[1].[2].value)` (expected `[2].value` instead of `[0].[1].[2]value`)
4) etc.

Note that the same bug now also happens when using "Send to Memory Window" on e.g. __locals and manually entered in-scope named variables in the watch window, which does not happen in 0.3.7.1.

This can produce pretty funny expressions on more complex objects:

<img width="1019" alt="Capture2" src="https://user-images.githubusercontent.com/16856443/184432389-60bd667a-2294-4c24-872b-e901d00a7f3e.PNG">

`&(((UString*)tokens._M_impl._M_start)[0].....[4].mLength)` (expected `[4].mLength` instead of `[0].....[4].mLength`)

Additionally, this regression also affects the "Add Watch" function now:

<img width="705" alt="Capture3" src="https://user-images.githubusercontent.com/16856443/184432885-24b7d188-b2a6-4906-9e81-2af5fe2a4813.PNG">

1) `commands._M_impl._M_start` (correct)
2) `commands._M_impl.._M_finish` (expected one single dot instead of two)
3) `commands._M_impl..._M_end_of_storage` (expected one single dot instead of three)
4) etc.

And "Add Watch" with the provided example code:

<img width="707" alt="Capture4" src="https://user-images.githubusercontent.com/16856443/184433985-a60c9f60-2652-488f-b871-ffe07da0c88e.PNG">

1) `arrayOfSomethings[0].value` (correct)
2) `arrayOfSomethings[0].[1].value` (expected `[1].value` instead of `[0].[1].value`)
3) `arrayOfSomethings[0].[1].[2].value` (expected `[2].value` instead of `[0].[1].[2].value`)
4) etc.

**Comment by x13pixels** [comment]
Fixed regression in 0.3.8.1.
